### PR TITLE
allows external style sheets by allowing https

### PR DESCRIPTION
**Pull request by Pierce01**

### CODE REVIEW

**Comment by Rapptz** [comment]
I don't see the point of this actually considering that CSS injection still works even after the CSP headers unless they've changed that recently?

**Comment by shikhir-arora** [comment]
They did change it on Canary - they may have reverted it though. It blocks on CSP for `unsafe-inline` and records the violation to Sentry. I actually noticed this more than a month ago, but it didn't do anything but throw a warning. 

They made the change today public and announced it in the testers guild, though I'm not sure if they reverted it as they said they would be for some changes. Either way, the code here does fix it. The loading happens right at the start, so nothing is loaded. It spawns a lot of annoying errors over CSS and ignoring CSP headers handles that.

**Comment by Pierce01** [comment]
Haven't reverted it to my knowledge, so imported style-sheets and images would still get blocked by the new policy on canary

**Comment by Pierce01** [comment]
as the new title says, this allows style sheets, images, fonts, etc to be loaded that are secure

**Comment by AlexFlipnote** [comment]
Due to this unsafe-inline, I've had to upload the images I want to use in a hidden channel in order to achieve the same URL as discordapp.com, just keeping that as a note.

Image

**Comment by leovoel** [comment]
thanks!

**Pull request merged**
